name: bevlioon
description: "Bevlioon is a simple and elegant movie exploration app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^6.0.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.1
  dio: ^5.9.0
  intl: ^0.20.2
  get_it: ^8.2.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  logger: ^2.6.1
  go_router: ^16.2.4
  flutter_svg: ^2.2.1
  collection: ^1.19.1
  pretty_dio_logger: ^1.4.0
  toastification: ^3.0.3
  infinite_scroll_pagination: ^5.1.1
  url_launcher: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
